version: '3'
services:
  db:
    container_name: backend-mysql
    image: mysql
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=devdb
      - MYSQL_ROOT_PASSWORD=devpassword
    ports:
      - '3306:3306'
    volumes:
      - backend-mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  backend-mysql:
    driver: local